strategy: dropbox

dropbox_app_key: AAAAAAAAAAAAAAA
dropbox_app_secret: BBBBBBBBBBBBBBB
dropbox_client_token: XXXXXXXXXXXXXXX
dropbox_client_secret: YYYYYYYYYYYYYYY

simple_note_user_name: you@email.com
simple_note_password: password