# The document store to use. Can be either 'dropbox' or 'simplenote', however
# currently only 'dropbox' is supported.
document_store: dropbox
# Time in minutes, after which to check for changes. Only happens after a request,
# so will not actually check every X minutes unless you're John Gruber.
# Dropbox kindly asks that you keep this at 5 or more.
delta_check_after: 5

# Dropbox API credentials
dropbox_app_key: AAAAAAAAAAAAAAA
dropbox_app_secret: BBBBBBBBBBBBBBB
dropbox_client_token: XXXXXXXXXXXXXXX
dropbox_client_secret: YYYYYYYYYYYYYYY

# SimpleNote not yet implemented :)
simple_note_username: you@email.com
simple_note_password: password

# Either the folder name (for Dropbox) or note tag (for SimpleNote)
# for articles and pages
articles_folder: articles
pages_folder: pages
