strategy: dropbox

dropbox_app_key: AAAAAAAAAAAAAAA
dropbox_app_secret: BBBBBBBBBBBBBBB
dropbox_client_token: XXXXXXXXXXXXXXX
dropbox_client_secret: YYYYYYYYYYYYYYY

# SimpleNote not yet implemented :)
simple_note_username: you@email.com
simple_note_password: password

# Either the folder name (Dropbox) or note tag (SimpleNote)
# for articles and pages
articles: articles
pages: pages